In [23]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [24]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [25]:
import pandas as pd
import time
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules

In [26]:
# Load transaction-encoded dataset
final_df = pd.read_csv("/content/pattern_recognition_preprocessed.csv")

print("Shape:", final_df.shape)
final_df.head()

Shape: (1608, 40)

,crime,date,time,location,latitude,longitude,land_use_type,weather,is_holiday,hour,...,loc_medical,loc_parking,loc_recreation,loc_religious,loc_residential,loc_road,loc_transport_hub,loc_urban_center,day_holiday,day_non_holiday
0,burglary,2019-12-31,08:17:00,mulgampola,7.280544,80.616500,General Urban,Cloudy,0,8,...,0,0,0,0,1,0,0,0,0,1
1,burglary,2020-01-04,02:00:00,car park,7.283445,80.619385,Commercial,Rainy,0,2,...,0,1,0,0,0,0,0,0,0,1
2,theft,2020-01-08,21:01:00,bus stand,7.256425,80.590461,Commercial,Rainy,1,21,...,0,0,0,0,0,0,1,0,1,0
3,vehicle theft,2020-01-10,12:10:00,aniwatte,7.290058,80.622438,General Urban,Cloudy,1,12,...,0,0,0,0,1,0,0,0,1,0
4,robbery,2020-01-11,02:39:00,dutugamunu mawatha,7.312344,80.645687,General Urban,Rainy,0,2,...,0,0,0,0,0,1,0,0,0,1

In [27]:
MIN_SUPPORT = 0.02     # 2%
MIN_CONFIDENCE = 0.6   # 60%

In [28]:
final_df.dtypes

crime                   object
date                    object
time                    object
location                object
latitude               float64
longitude              float64
land_use_type           object
weather                 object
is_holiday               int64
hour                     int64
day_of_week              int64
month                    int64
time_bucket             object
location_category       object
day_type                object
crime_burglary           int64
crime_drugs              int64
crime_robbery            int64
crime_stabbing           int64
crime_theft              int64
crime_vehicle theft      int64
time_afternoon           int64
time_late_night          int64
time_morning             int64
time_night               int64
loc_cemetery             int64
loc_commercial           int64
loc_education            int64
loc_government           int64
loc_hospitality          int64
loc_medical              int64
loc_parking              int64
loc_recreation           int64
loc_religious            int64
loc_residential          int64
loc_road                 int64
loc_transport_hub        int64
loc_urban_center         int64
day_holiday              int64
day_non_holiday          int64
dtype: object

In [29]:
# Keep ONLY binary columns (0/1)
transaction_df_bin = final_df.select_dtypes(include=['int64'])

In [30]:
transaction_df_bin = transaction_df_bin.astype(bool)
transaction_df_bin,

(      is_holiday  hour  day_of_week  month  crime_burglary  crime_drugs  \
 0          False  True         True   True            True        False
 1          False  True         True   True            True        False
 2           True  True         True   True           False        False
 3           True  True         True   True           False        False
 4          False  True         True   True           False        False
 ...          ...   ...          ...    ...             ...          ...
 1603       False  True         True   True           False         True
 1604       False  True         True   True           False         True
 1605       False  True         True   True           False        False
 1606       False  True         True   True           False        False
 1607       False  True         True   True           False        False

       crime_robbery  crime_stabbing  crime_theft  crime_vehicle theft  ...  \
 0             False           False        False                False  ...
 1             False           False        False                False  ...
 2             False           False         True                False  ...
 3             False           False        False                 True  ...
 4              True           False        False                False  ...
 ...             ...             ...          ...                  ...  ...
 1603          False           False        False                False  ...
 1604          False           False        False                False  ...
 1605           True           False        False                False  ...
 1606           True           False        False                False  ...
 1607          False            True        False                False  ...

       loc_medical  loc_parking  loc_recreation  loc_religious  \
 0           False        False           False          False
 1           False         True           False          False
 2           False        False           False          False
 3           False        False           False          False
 4           False        False           False          False
 ...           ...          ...             ...            ...
 1603        False        False           False          False
 1604        False        False           False          False
 1605        False        False           False          False
 1606        False        False           False          False
 1607        False        False           False          False

       loc_residential  loc_road  loc_transport_hub  loc_urban_center  \
 0                True     False              False             False
 1               False     False              False             False
 2               False     False               True             False
 3                True     False              False             False
 4               False      True              False             False
 ...               ...       ...                ...               ...
 1603             True     False              False             False
 1604            False      True              False             False
 1605            False     False              False             False
 1606            False     False              False             False
 1607             True     False              False             False

       day_holiday  day_non_holiday
 0           False             True
 1           False             True
 2            True            False
 3            True            False
 4           False             True
 ...           ...              ...
 1603        False             True
 1604        False             True
 1605        False             True
 1606        False             True
 1607        False             True

 [1608 rows x 29 columns],)

In [31]:
# -------- APRIORI --------
start_time = time.time()

frequent_itemsets_apriori = apriori(
    transaction_df_bin,
    min_support=MIN_SUPPORT,
    use_colnames=True
)

rules_apriori = association_rules(
    frequent_itemsets_apriori,
    metric="confidence",
    min_threshold=MIN_CONFIDENCE
)

apriori_time = time.time() - start_time

print("Apriori completed")

rules_apriori = rules_apriori.dropna()  # removes any rows with NaN metrics

Apriori completed

/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [32]:
# -------- FP-GROWTH --------
start_time = time.time()

frequent_itemsets_fp = fpgrowth(
    transaction_df_bin,
    min_support=MIN_SUPPORT,
    use_colnames=True
)

rules_fp = association_rules(
    frequent_itemsets_fp,
    metric="confidence",
    min_threshold=MIN_CONFIDENCE
)

fp_time = time.time() - start_time

print("FP-Growth completed")

FP-Growth completed

/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [33]:
benchmark_results = pd.DataFrame({
    "Model": ["Apriori", "FP-Growth"],
    "Execution Time (seconds)": [apriori_time, fp_time],
    "Frequent Itemsets Count": [
        len(frequent_itemsets_apriori),
        len(frequent_itemsets_fp)
    ],
    "Association Rules Count": [
        len(rules_apriori),
        len(rules_fp)
    ],
    "Average Confidence": [
        rules_apriori["confidence"].mean() if not rules_apriori.empty else 0,
        rules_fp["confidence"].mean() if not rules_fp.empty else 0
    ]
})

benchmark_results

,Model,Execution Time (seconds),Frequent Itemsets Count,Association Rules Count,Average Confidence
0,Apriori,0.128284,1189,4630,0.918479
1,FP-Growth,6.957987,1189,4630,0.918479

In [34]:
best_model = "FP-Growth" if fp_time < apriori_time else "Apriori"

print("Selected Best Model:", best_model)

Selected Best Model: Apriori

In [35]:
benchmark_results.to_csv("pattern_mining_benchmark_results.csv", index=False)

In [36]:
if best_model == "FP-Growth":
    rules_fp.sort_values(by="confidence", ascending=False)\
            .to_csv("final_fp_growth_rules.csv", index=False)
else:
    rules_apriori.sort_values(by="confidence", ascending=False)\
                 .to_csv("final_apriori_rules.csv", index=False)

**Apriori was selected due to its interpretability, stable performance, and suitability for explainable crime pattern detection.**

In [40]:
from getpass import getpass
import os

# Ask for GitHub token securely
token = getpass("Enter your GitHub token: ")

# Your GitHub username and repo info
username = "vicha1234"
owner = "Chanthul4054"
repo_name = "E-Policing-An-Integrated-Spatio-Temporal-Crime-Forecasting-and-Decision-Support-System"
branch_name = "Pattern-Recognition-System"

#Construct HTTPS URL with token (kept hidden)
repo_url = f"https://{username}:{token}@github.com/{owner}/{repo_name}.git"

#Clone the repo
!git clone {repo_url}

#Change directory to repo
%cd {repo_name}

#Checkout the desired branch
!git fetch origin
!git checkout {branch_name}

#Copy your notebook from Colab environment to repo folder
!cp "/content/drive/MyDrive/Colab Notebooks/benchmark_association_models.ipynb" .

#Add notebook to staging
!git add benchmark_association_models.ipynb

# Commit changes
!git commit -m "Implement model benchmarking"

#Push to GitHub safely
!git push origin {branch_name}

Enter your GitHub token: ··········
Cloning into 'E-Policing-An-Integrated-Spatio-Temporal-Crime-Forecasting-and-Decision-Support-System'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 109 (delta 33), reused 44 (delta 7), pack-reused 0 (from 0)
Receiving objects: 100% (109/109), 469.83 KiB | 2.57 MiB/s, done.
Resolving deltas: 100% (33/33), done.
/content/E-Policing-An-Integrated-Spatio-Temporal-Crime-Forecasting-and-Decision-Support-System
Branch 'Pattern-Recognition-System' set up to track remote branch 'Pattern-Recognition-System' from 'origin'.
Switched to a new branch 'Pattern-Recognition-System'
cp: cannot stat '/content/drive/MyDrive/Colab Notebooks/benchmark_association_models.ipynb': No such file or directory
fatal: pathspec 'benchmark_association_models.ipynb' did not match any files
On branch Pattern-Recognition-System
Your branch is up to date with 'origin/Pattern-Recognition-System'.

nothing to commit, working tree clean
Everything up-to-date

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [43]:
!ls "/content/drive/MyDrive/Colab Notebooks/"

'2425610 (3).ipynb'		      Pattern_Recognition_Preprocessing.ipynb
'2425610 (4).ipynb'		      Tutorial_1.ipynb
 2425610.ipynb			      Untitled0.ipynb
 benchmark_association_models.ipynb   Untitled1.ipynb
'Copy of Lesson 4.ipynb'	      Untitled3.ipynb
'Copy of Lesson 5.ipynb'	      Week1.ipynb
 Pattern_recognition.ipynb	      week2.ipynb

In [44]:
!cp "/content/drive/MyDrive/Colab Notebooks/benchmark_association_models.ipynb" .

In [ ]:
%cd E-Policing-An-Integrated-Spatio-Temporal-Crime-Forecasting-and-Decision-Support-System
!git checkout Pattern-Recognition-System
!cp "/content/drive/MyDrive/Colab Notebooks/benchmark_association_models.ipynb" .
!git add benchmark_association_models.ipynb
!git commit -m "Add benchmark notebook for Apriori vs FP-Growth comparison"
!git push origin Pattern-Recognition-System