In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/CrimePredictionSystem/CrimeData_Final.csv')

In [4]:
#Converts date to a proper datetime object
df['date']= pd.to_datetime(df['date'])

In [5]:
df.head()

,crime,location,date,sex,victim_ethnicity,victim_age,time,weather,latitude,longitude,...,gn_pcode,gn_population,gn_distance_m,victim_ethnicity,DS_Division,Avg_Household_Income,Unemployment_Rate,Building_Density,Road_Density,Land_Area_Density
0,burglary,mulgampola,2019-12-31,f,muslim,54,8:17:00,Cloudy,7.280544,80.616500,...,LK2130170,21826,311.8,muslim,Gangawata Korale,124797,4.55,740.9,29.5,16.06
1,burglary,car park,2020-01-04,m,sinhala,42,2:00:00,Rainy,7.283445,80.619385,...,LK2130105,8913,352.4,sinhala,Gangawata Korale,111768,4.53,892.7,29.8,19.76
2,theft,bus stand,2020-01-08,f,sinhala,20,21:01:00,Rainy,7.256425,80.590461,...,LK2139135,16411,518.6,sinhala,Udunuwara,69786,5.57,548.4,16.6,11.66
3,vehicle theft,aniwatte,2020-01-10,m,sinhala,29,12:10:00,Cloudy,7.290058,80.622438,...,LK2130100,1107,381.5,sinhala,Gangawata Korale,107410,4.68,881.2,24.1,17.18
4,robbery,dutugamunu mawatha,2020-01-11,m,sinhala,59,2:39:00,Rainy,7.312344,80.645687,...,LK2130050,1293,322.6,sinhala,Gangawata Korale,120663,4.71,585.4,24.0,9.45

In [6]:
print("Rows, Columns =",df.shape)

Rows, Columns = (1608, 24)

In [7]:
df.columns.tolist()

['crime',
 'location',
 'date',
 'sex',
 'victim_ethnicity',
 'victim_age',
 'time',
 'weather',
 'latitude',
 'longitude',
 'holiday_name',
 'is_holiday',
 'land_use_type',
 'gn_division',
 'gn_pcode',
 'gn_population',
 'gn_distance_m',
 'victim_ethnicity ',
 'DS_Division',
 'Avg_Household_Income',
 'Unemployment_Rate',
 'Building_Density',
 'Road_Density',
 'Land_Area_Density']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   crime                 1608 non-null   object
 1   location              1608 non-null   object
 2   date                  1608 non-null   datetime64[ns]
 3   sex                   1608 non-null   object
 4   victim_ethnicity      1608 non-null   object
 5   victim_age            1608 non-null   int64
 6   time                  1608 non-null   object
 7   weather               1608 non-null   object
 8   latitude              1608 non-null   float64
 9   longitude             1608 non-null   float64
 10  holiday_name          1608 non-null   object
 11  is_holiday            1608 non-null   int64
 12  land_use_type         1608 non-null   object
 13  gn_division           1608 non-null   object
 14  gn_pcode              1608 non-null   object
 15  gn_population         1608 non-null   int64
 16  gn_distance_m         1608 non-null   float64
 17  victim_ethnicity      1608 non-null   object
 18  DS_Division           1608 non-null   object
 19  Avg_Household_Income  1608 non-null   int64
 20  Unemployment_Rate     1608 non-null   float64
 21  Building_Density      1608 non-null   float64
 22  Road_Density          1608 non-null   float64
 23  Land_Area_Density     1608 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(4), object(12)
memory usage: 301.6+ KB

In [9]:
df.describe(include="all")

,crime,location,date,sex,victim_ethnicity,victim_age,time,weather,latitude,longitude,...,gn_pcode,gn_population,gn_distance_m,victim_ethnicity,DS_Division,Avg_Household_Income,Unemployment_Rate,Building_Density,Road_Density,Land_Area_Density
count,1608,1608,1608,1608,1608,1608.000000,1608,1608,1608.000000,1608.000000,...,1608,1608.000000,1608.000000,1608,1608,1608.000000,1608.000000,1608.000000,1608.000000,1608.000000
unique,6,125,NaN,3,3,NaN,916,3,NaN,NaN,...,72,NaN,NaN,3,11,NaN,NaN,NaN,NaN,NaN
top,burglary,bus stand,NaN,m,sinhala,NaN,13:31:00,Rainy,NaN,NaN,...,LK2130145,NaN,NaN,sinhala,Gangawata Korale,NaN,NaN,NaN,NaN,NaN
freq,462,87,NaN,1171,1343,NaN,6,1361,NaN,NaN,...,258,NaN,NaN,1343,1485,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2022-11-10 14:58:12.537313280,NaN,NaN,42.602612,NaN,NaN,7.285506,80.633042,...,NaN,8630.593284,398.776306,NaN,NaN,111520.689055,4.633800,676.903607,17.181157,13.717693
min,NaN,NaN,2019-12-31 00:00:00,NaN,NaN,15.000000,NaN,NaN,7.094806,80.528761,...,NaN,926.000000,6.700000,NaN,NaN,49472.000000,4.280000,0.000000,0.000000,0.000000
25%,NaN,NaN,2021-10-16 18:00:00,NaN,NaN,32.000000,NaN,NaN,7.279031,80.624353,...,NaN,2198.000000,220.675000,NaN,NaN,107400.250000,4.410000,424.375000,13.200000,8.997500
50%,NaN,NaN,2023-01-04 12:00:00,NaN,NaN,42.000000,NaN,NaN,7.289164,80.634393,...,NaN,6925.000000,316.150000,NaN,NaN,113834.500000,4.530000,772.800000,18.800000,15.800000
75%,NaN,NaN,2023-12-12 06:00:00,NaN,NaN,52.000000,NaN,NaN,7.294233,80.639486,...,NaN,13050.000000,445.600000,NaN,NaN,119886.000000,4.650000,883.800000,21.700000,19.770000
max,NaN,NaN,2025-09-23 00:00:00,NaN,NaN,78.000000,NaN,NaN,7.499662,80.764916,...,NaN,22268.000000,8483.300000,NaN,NaN,126467.000000,8.180000,1480.600000,30.100000,22.730000
std,NaN,NaN,NaN,NaN,NaN,13.871646,NaN,NaN,0.025415,0.021201,...,NaN,6767.678765,640.411182,NaN,NaN,13205.932987,0.507417,356.217201,6.623979,6.903447

##Identifying Unique values in each colummn

In [10]:
categorical_cols =  ['crime',
 'location',
 'date',
 'sex',
 'victim_ethnicity',
 'victim_age',
 'time',
 'weather',
 'latitude',
 'longitude',
 'holiday_name',
 'is_holiday',
 'land_use_type',
 'gn_division',
 'gn_pcode',
 'gn_population',
 'gn_distance_m',
 'victim_ethnicity ',
 'DS_Division',
 'Avg_Household_Income',
 'Unemployment_Rate',
 'Building_Density',
 'Road_Density',
 'Land_Area_Density']
print("Unique values")
for col in categorical_cols:
  print(f"{col} : ",df[col].unique())
  # print(f"{col} : ",df[col].nunique())

Unique values
crime :  ['burglary' 'theft' 'vehicle theft' 'robbery' 'drugs' 'stabbing']
location :  ['mulgampola' 'car park' 'bus stand' 'aniwatte' 'dutugamunu mawatha'
 'mahamaya primary' 'bahirawakanda' 'thannekumbura' 'dangolla junction'
 'kandy city centre' 'lewella bangalaawatte' 'meekanuwa watarauma'
 'wattaranthanne ground' 'asgiriya stadium' 'gatambe junction'
 'dalada maligawa' 'yatinuwara street' 'hanthane kadurata malshalawa'
 'pattiyakale watte' 'municipal indoor sports complex'
 'pathanawatte heerassagala' 'ogastawatte' 'mahaiyawa' 'gatambe bridge'
 'dodamwela' 'buwelikada' 'kotugodalla road' 'ampitiya town' 'bowalawatte'
 'thalathuoya road' 'peradeniya road' 'heerassagala junction' 'udabowala'
 'post office' "people's bank" 'kandy hospital' 'hewaheta' 'train station'
 'galkaduwa junction' 'sri wickramasinghe mawatha' 'goerge.e.silva lane'
 'hanthane' 'william gopallawa lane' 'common market complex'
 'mada bowala angampitiya' 'bogambara' 'nuwarawela ampitiya' 'nagasthanne'
 'welikanda' 'new queens hotel' 'police station'
 'sirimawo bandaranayake lane' 'katugasthota road' 'polgolla'
 'dharmapala road lewella' 'watapuluwa' 'hanthane town' 'suduhumpola'
 'lake house hotel' 'heerassagala' '2nd rajasinghe lane'
 'rajapihilla road' 'bogambara official police stayhouse' 'hewaheta road'
 'asgiriya' 'walespark' 'goerge.e. silva lane' 'd.s senanayake lane'
 'primrose gardens' 'mahaiyawa cemetery' 'dangolla' 'central market'
 'sky gate hotel' 'hanthane road' 'kandy town' 'dharmasena lane'
 'joy boat' 'peradeniya town' 'kandy mosque' 'golden crown'
 'paradise park' 'aruppala' 'kotugodalla street' 'dalada street'
 'colombo street' 'lady golden road' 'lewella town' 'dodamwela bridge'
 'gurudeniya' 'highschool' 'kingswood' 'katukale' 'gatambe'
 'hospital street' 'sri sumangala mawatha' 'deiyanwela' 'yatinuwara lane'
 'lake round' 'uda peradeniya bowalawatte' 'urawela junction'
 'peradeniya kfc' 'thilakawardhana' 'bogambara prison' 'apiit campus'
 'wewathanne road' 'wattegama' 'katugasthota' 'malwatte'
 'pitakanda kanaththa' 'amaya hotel' 'sahas uyana' 'sangamiththa college'
 'wagolla lewella' 'rajapihilla' 'lewella gangaramaya'
 'ampitiya udawela kanda' 'torrington' 'rosawatte' 'vidyartha college'
 'wadugodapitiya' 'provincial education department'
 'watapuluwa prithi mawatha' 'poornawatte' 'mapanawathura' 'ampitiya']
date :  <DatetimeArray>
['2019-12-31 00:00:00', '2020-01-04 00:00:00', '2020-01-08 00:00:00',
 '2020-01-10 00:00:00', '2020-01-11 00:00:00', '2020-01-12 00:00:00',
 '2020-01-15 00:00:00', '2020-01-16 00:00:00', '2020-01-18 00:00:00',
 '2020-01-19 00:00:00',
 ...
 '2025-05-07 00:00:00', '2025-05-15 00:00:00', '2025-06-08 00:00:00',
 '2025-06-10 00:00:00', '2025-06-13 00:00:00', '2025-07-30 00:00:00',
 '2025-08-16 00:00:00', '2025-09-13 00:00:00', '2025-09-17 00:00:00',
 '2025-09-23 00:00:00']
Length: 1046, dtype: datetime64[ns]
sex :  ['f' 'm' 'foreign couple']
victim_ethnicity :  ['muslim' 'sinhala' 'tamil']
victim_age :  [54 42 20 29 59 45 36 47 27 26 51 73 30 25 21 17 44 18 31 52 33 72 43 24
 40 57 35 53 19 28 38 46 37 68 58 41 76 34 63 23 50 55 56 39 74 61 75 48
 49 60 66 15 64 70 32 65 22 69 77 78 62 16 71 67]
time :  ['8:17:00' '2:00:00' '21:01:00' '12:10:00' '2:39:00' '1:19:00' '19:57:00'
 '9:18:00' '10:58:00' '16:13:00' '10:39:00' '12:45:00' '10:47:00'
 '0:15:00' '7:42:00' '22:43:00' '22:44:00' '8:10:00' '8:28:00' '11:06:00'
 '21:09:00' '19:42:00' '20:21:00' '5:30:00' '23:39:00' '1:02:00' '4:01:00'
 '3:33:00' '3:35:00' '21:56:00' '5:33:00' '18:09:00' '16:52:00' '15:50:00'
 '18:23:00' '0:14:00' '1:47:00' '23:14:00' '8:29:00' '6:14:00' '5:00:00'
 '8:19:00' '0:34:00' '4:18:00' '13:31:00' '7:49:00' '0:40:00' '19:19:00'
 '7:06:00' '12:31:00' '21:07:00' '22:08:00' '12:59:00' '13:36:00'
 '15:55:00' '5:05:00' '21:44:00' '6:39:00' '4:49:00' '22:16:00' '15:59:00'
 '22:02:00' '11:29:00' '21:23:00' '1:38:00' '12:25:00' '9:49:00'
 '19:49:00' '23:08:00' '6:40:00' '6:27:00' '12:46:00' '2:05:00' '22:48:00'
 '22:01:00' '19:52:00' '7:35:00' '23:40:00' '12:13:00' '1:50:00'
 '15:22:00' '4:36:00' '14:04:00' '20:11:00' '16:33:00' '17:34:00'
 '15:13:00' '8:49:00' '5:09:00' '23:31:00' '12:14:00' '22:19:00'
 '22:52:00' '9:50:00' '19:45:00' '6:11:00' '2:30:00' '21:34:00' '13:55:00'
 '20:20:00' '23:27:00' '12:05:00' '18:22:00' '18:58:00' '19:26:00'
 '13:30:00' '16:07:00' '22:25:00' '4:27:00' '6:07:00' '21:59:00' '9:02:00'
 '17:37:00' '14:26:00' '19:05:00' '16:36:00' '20:09:00' '10:38:00'
 '16:09:00' '17:53:00' '21:53:00' '3:05:00' '20:06:00' '20:12:00'
 '5:27:00' '12:58:00' '13:34:00' '1:30:00' '17:57:00' '11:47:00'
 '10:11:00' '12:50:00' '14:23:00' '15:04:00' '20:40:00' '16:54:00'
 '10:32:00' '6:42:00' '15:37:00' '23:12:00' '4:43:00' '4:50:00' '8:42:00'
 '17:14:00' '10:31:00' '10:04:00' '6:17:00' '12:40:00' '13:35:00'
 '13:32:00' '5:49:00' '11:50:00' '22:59:00' '14:51:00' '18:10:00'
 '1:58:00' '2:54:00' '11:45:00' '7:14:00' '13:09:00' '4:19:00' '0:58:00'
 '5:11:00' '20:51:00' '15:47:00' '4:58:00' '20:26:00' '0:59:00' '13:57:00'
 '12:22:00' '11:13:00' '20:16:00' '1:21:00' '9:14:00' '17:45:00'
 '23:59:00' '10:10:00' '6:36:00' '4:34:00' '10:09:00' '17:30:00' '7:52:00'
 '3:23:00' '2:45:00' '9:13:00' '14:52:00' '22:03:00' '18:51:00' '4:25:00'
 '6:22:00' '17:47:00' '9:47:00' '13:19:00' '14:05:00' '7:21:00' '16:38:00'
 '13:14:00' '1:07:00' '3:43:00' '9:52:00' '3:32:00' '6:32:00' '23:56:00'
 '16:28:00' '7:20:00' '3:38:00' '20:34:00' '22:11:00' '5:37:00' '11:21:00'
 '13:47:00' '23:23:00' '3:46:00' '16:57:00' '9:20:00' '15:15:00'
 '10:16:00' '7:40:00' '21:48:00' '17:32:00' '22:35:00' '3:47:00' '6:52:00'
 '22:37:00' '0:20:00' '15:44:00' '19:31:00' '10:30:00' '9:26:00'
 '14:58:00' '18:50:00' '9:58:00' '10:53:00' '23:28:00' '14:37:00'
 '9:24:00' '15:12:00' '19:27:00' '11:18:00' '14:07:00' '5:53:00' '0:27:00'
 '2:17:00' '22:42:00' '16:31:00' '0:37:00' '16:40:00' '8:53:00' '16:51:00'
 '7:07:00' '1:51:00' '3:40:00' '17:52:00' '7:50:00' '17:20:00' '0:30:00'
 '10:15:00' '20:48:00' '23:15:00' '14:17:00' '14:10:00' '16:04:00'
 '13:38:00' '5:44:00' '6:56:00' '1:56:00' '14:43:00' '9:11:00' '7:45:00'
 '12:48:00' '2:14:00' '20:44:00' '5:17:00' '9:55:00' '10:46:00' '18:07:00'
 '3:13:00' '15:58:00' '16:43:00' '18:37:00' '9:07:00' '7:37:00' '1:00:00'
 '7:09:00' '19:59:00' '14:03:00' '0:09:00' '5:31:00' '22:53:00' '16:39:00'
 '6:55:00' '22:57:00' '1:20:00' '13:17:00' '13:02:00' '15:05:00'
 '15:39:00' '18:00:00' '23:33:00' '21:52:00' '6:18:00' '6:30:00' '4:28:00'
 '5:51:00' '5:56:00' '11:42:00' '6:09:00' '0:52:00' '3:04:00' '11:57:00'
 '21:30:00' '1:54:00' '16:41:00' '18:52:00' '0:17:00' '3:24:00' '21:17:00'
 '21:54:00' '22:32:00' '9:28:00' '0:29:00' '6:35:00' '22:45:00' '22:38:00'
 '23:20:00' '11:27:00' '23:13:00' '7:17:00' '12:39:00' '4:23:00'
 '14:33:00' '6:08:00' '13:52:00' '13:22:00' '19:03:00' '19:07:00'
 '9:44:00' '14:53:00' '18:03:00' '23:42:00' '0:18:00' '11:58:00'
 '15:16:00' '17:19:00' '20:24:00' '2:01:00' '3:28:00' '15:33:00'
 '19:37:00' '6:43:00' '5:50:00' '15:54:00' '11:30:00' '6:51:00' '15:08:00'
 '9:43:00' '16:29:00' '11:40:00' '1:12:00' '12:53:00' '1:11:00' '3:53:00'
 '7:13:00' '16:14:00' '4:56:00' '10:49:00' '1:52:00' '5:43:00' '2:57:00'
 '20:04:00' '19:06:00' '16:58:00' '4:04:00' '21:14:00' '0:39:00'
 '23:09:00' '6:48:00' '17:18:00' '10:55:00' '15:20:00' '15:46:00'
 '20:32:00' '11:37:00' '8:39:00' '22:20:00' '19:11:00' '5:26:00'
 '14:11:00' '13:41:00' '3:57:00' '18:11:00' '4:13:00' '3:48:00' '17:59:00'
 '20:50:00' '14:54:00' '20:52:00' '9:17:00' '21:28:00' '12:42:00'
 '16:35:00' '13:53:00' '21:13:00' '12:36:00' '22:21:00' '16:20:00'
 '12:11:00' '20:31:00' '13:03:00' '22:47:00' '3:39:00' '9:19:00'
 '21:43:00' '8:47:00' '20:10:00' '21:33:00' '8:32:00' '8:37:00' '18:17:00'
 '15:45:00' '3:27:00' '13:43:00' '4:57:00' '13:42:00' '21:35:00'
 '14:41:00' '5:41:00' '16:50:00' '20:39:00' '19:09:00' '21:18:00'
 '12:23:00' '13:26:00' '20:00:00' '15:31:00' '21:02:00' '21:25:00'
 '7:53:00' '9:25:00' '23:05:00' '6:28:00' '7:39:00' '5:48:00' '6:23:00'
 '19:04:00' '5:59:00' '14:25:00' '14:50:00' '19:58:00' '20:13:00'
 '16:03:00' '13:11:00' '14:42:00' '8:31:00' '12:47:00' '13:27:00'
 '21:24:00' '22:50:00' '9:38:00' '14:16:00' '16:22:00' '8:51:00'
 '11:33:00' '13:49:00' '14:24:00' '22:54:00' '10:59:00' '8:24:00'
 '10:48:00' '20:30:00' '19:10:00' '19:33:00' '19:44:00' '15:18:00'
 '18:55:00' '19:23:00' '9:09:00' '5:25:00' '18:53:00' '22:27:00' '8:59:00'
 '9:04:00' '16:11:00' '20:22:00' '16:32:00' '8:52:00' '20:23:00'
 '17:07:00' '11:26:00' '11:34:00' '23:11:00' '15:53:00' '10:02:00'
 '7:56:00' '13:25:00' '5:55:00' '18:32:00' '9:36:00' '11:38:00' '15:56:00'
 '18:01:00' '15:17:00' '8:27:00' '15:36:00' '11:07:00' '18:27:00'
 '15:23:00' '17:50:00' '21:22:00' '20:56:00' '20:14:00' '2:33:00'
 '20:35:00' '9:39:00' '13:00:00' '11:56:00' '10:06:00' '11:01:00'
 '19:28:00' '15:57:00' '18:20:00' '18:21:00' '18:40:00' '4:38:00'
 '19:40:00' '16:21:00' '17:00:00' '18:05:00' '16:47:00' '7:12:00'
 '19:34:00' '3:56:00' '20:05:00' '4:54:00' '18:57:00' '23:30:00'
 '10:52:00' '14:57:00' '8:09:00' '11:55:00' '13:07:00' '17:13:00'
 '13:51:00' '6:00:00' '21:12:00' '1:31:00' '7:36:00' '10:13:00' '10:20:00'
 '8:34:00' '3:42:00' '9:40:00' '20:28:00' '17:29:00' '22:07:00' '15:00:00'
 '16:45:00' '13:39:00' '19:02:00' '19:08:00' '15:25:00' '7:46:00'
 '21:27:00' '12:09:00' '20:33:00' '17:02:00' '17:16:00' '1:08:00'
 '2:52:00' '10:51:00' '8:05:00' '22:33:00' '17:31:00' '17:48:00' '8:55:00'
 '23:36:00' '18:49:00' '11:24:00' '14:45:00' '8:35:00' '18:30:00'
 '7:34:00' '9:06:00' '12:34:00' '2:25:00' '18:42:00' '8:48:00' '19:21:00'
 '4:12:00' '14:27:00' '14:20:00' '15:03:00' '7:51:00' '17:05:00'
 '16:00:00' '19:20:00' '23:17:00' '15:06:00' '14:13:00' '18:19:00'
 '4:48:00' '12:28:00' '8:50:00' '2:51:00' '11:31:00' '2:03:00' '15:19:00'
 '13:46:00' '8:18:00' '13:58:00' '17:04:00' '11:51:00' '8:07:00'
 '14:40:00' '16:02:00' '14:02:00' '9:16:00' '14:34:00' '12:02:00'
 '8:16:00' '3:19:00' '22:58:00' '16:48:00' '14:12:00' '6:59:00' '15:09:00'
 '3:25:00' '15:27:00' '19:39:00' '11:59:00' '9:15:00' '9:57:00' '14:19:00'
 '16:26:00' '15:34:00' '14:29:00' '13:54:00' '21:29:00' '2:21:00'
 '10:28:00' '21:57:00' '16:05:00' '2:10:00' '7:23:00' '5:22:00' '18:33:00'
 '17:10:00' '0:07:00' '3:51:00' '14:06:00' '18:26:00' '22:18:00' '5:07:00'
 '11:10:00' '15:01:00' '15:11:00' '17:49:00' '2:37:00' '12:43:00'
 '15:10:00' '19:25:00' '19:16:00' '11:16:00' '4:05:00' '17:28:00'
 '18:31:00' '21:46:00' '21:51:00' '12:32:00' '9:53:00' '13:18:00'
 '6:24:00' '16:27:00' '7:25:00' '12:55:00' '18:35:00' '18:46:00'
 '14:00:00' '15:29:00' '13:59:00' '11:49:00' '17:01:00' '5:39:00'
 '11:43:00' '5:46:00' '15:38:00' '21:15:00' '11:52:00' '9:41:00'
 '15:32:00' '11:39:00' '12:35:00' '11:19:00' '21:10:00' '11:17:00'
 '17:11:00' '19:41:00' '10:03:00' '12:07:00' '19:54:00' '20:03:00'
 '16:56:00' '13:24:00' '13:50:00' '17:25:00' '8:45:00' '19:50:00'
 '15:42:00' '2:35:00' '21:32:00' '17:56:00' '17:12:00' '15:21:00'
 '18:13:00' '19:15:00' '20:46:00' '21:49:00' '12:26:00' '20:07:00'
 '15:24:00' '10:43:00' '16:06:00' '16:24:00' '10:00:00' '16:34:00'
 '20:38:00' '8:06:00' '19:01:00' '10:29:00' '12:27:00' '18:24:00'
 '17:38:00' '9:33:00' '8:14:00' '13:15:00' '18:16:00' '19:43:00'
 '22:06:00' '22:12:00' '22:34:00' '7:57:00' '15:40:00' '7:58:00'
 '14:08:00' '11:41:00' '14:01:00' '18:34:00' '12:16:00' '16:55:00'
 '16:16:00' '17:03:00' '13:23:00' '7:59:00' '18:08:00' '8:23:00'
 '13:20:00' '15:02:00' '0:51:00' '7:38:00' '17:15:00' '10:07:00'
 '16:19:00' '10:27:00' '8:57:00' '4:55:00' '6:01:00' '10:12:00' '11:00:00'
 '9:12:00' '17:08:00' '6:57:00' '17:06:00' '20:25:00' '19:22:00'
 '16:49:00' '10:14:00' '22:23:00' '9:35:00' '14:44:00' '21:05:00'
 '11:03:00' '17:46:00' '15:30:00' '21:41:00' '8:08:00' '15:41:00'
 '16:10:00' '7:29:00' '17:35:00' '18:56:00' '4:16:00' '21:06:00'
 '16:17:00' '15:28:00' '22:10:00' '13:05:00' '14:21:00' '20:59:00'
 '17:42:00' '22:04:00' '11:02:00' '14:18:00' '20:36:00' '14:47:00'
 '7:31:00' '18:45:00' '21:42:00' '18:02:00' '23:38:00' '9:00:00' '9:59:00'
 '10:44:00' '19:00:00' '10:57:00' '12:19:00' '13:08:00' '16:25:00'
 '8:20:00' '12:30:00' '10:05:00' '14:09:00' '4:07:00' '12:57:00'
 '18:38:00' '18:44:00' '17:36:00' '3:07:00' '21:39:00' '14:35:00'
 '8:25:00' '11:35:00' '17:33:00' '9:32:00' '15:07:00' '2:22:00' '16:46:00'
 '14:31:00' '8:46:00' '22:46:00' '20:42:00' '10:42:00' '10:54:00'
 '15:35:00' '19:17:00' '14:39:00' '9:10:00' '14:22:00' '13:01:00'
 '8:03:00' '20:37:00' '23:01:00' '12:06:00' '11:08:00' '7:01:00' '2:49:00'
 '8:02:00' '11:05:00' '11:04:00' '8:36:00' '6:10:00' '5:36:00' '13:12:00'
 '7:00:00' '14:30:00' '9:34:00' '3:29:00' '14:46:00' '4:31:00' '19:51:00'
 '1:29:00' '20:53:00' '5:14:00' '7:16:00' '22:36:00' '8:15:00' '22:49:00'
 '9:54:00' '5:15:00' '13:48:00' '6:06:00' '6:29:00' '10:17:00' '10:26:00'
 '9:27:00' '6:20:00' '19:18:00' '1:53:00' '5:12:00' '6:46:00' '5:28:00'
 '9:48:00' '12:18:00' '22:09:00' '2:18:00' '7:15:00' '17:22:00' '22:39:00'
 '18:36:00' '12:52:00' '9:37:00' '1:34:00' '10:19:00' '9:42:00' '13:37:00'
 '5:20:00' '11:09:00' '4:32:00' '20:54:00' '18:29:00' '4:51:00' '5:42:00'
 '4:35:00' '12:56:00' '7:48:00' '9:46:00' '18:59:00']
weather :  ['Cloudy' 'Rainy' 'Sunny']
latitude :  [7.28054354 7.28344486 7.25642501 ... 7.29034078 7.29218587 7.27933524]
longitude :  [80.61650015 80.61938468 80.59046053 ... 80.63356268 80.63347549
 80.64419566]
holiday_name :  ['Non-Holiday' 'Eid al-Adha' 'Adhi Vap Full Moon Poya Day'
 'Tamil Thai Pongal Day' 'Maha Sivarathri Day' 'Special Public Holiday'
 'Esala Full Moon Poya Day' 'Sinhala and Tamil New Year' 'Eid al-Fitr'
 'Vesak Full Moon Poya Day' 'Nawam Full Moon Poya Day'
 'Medin Full Moon Poya Day' 'Duruthu Full Moon Poya Day'
 "Prophet's Birthday" 'Vap Full Moon Poya Day' 'Deepavali Festival Day'
 'Day Before Sinhala and Tamil New Year' 'Christmas Day' 'Good Friday'
 'Independence Day' 'Poson Full Moon Poya Day' 'Nikini Full Moon Poya Day'
 'Il Full Moon Poya Day' 'Unduvap Full Moon Poya Day'
 "International Workers' Day" 'Bak Full Moon Poya Day'
 'Binara Full Moon Poya Day' 'Day Following Vesak Full Moon Poya Day']
is_holiday :  [0 1]
land_use_type :  ['General Urban' 'Commercial' 'Residential' 'Recreational']
gn_division :  ['Welata' 'Katukele West' 'Penideniya' 'Aniwatta East' 'Aruppala East'
 'Suduhumpala West' 'Mahaiyawa' 'Boowelikada' 'Asgiriya' 'Thennakumbura'
 'Bowala' 'Mahanuwara' 'Thalwatta' 'Ampitiya Udagama North'
 'Thalathuoya East' 'Poorna Watta West' 'Bogambara' 'Ihala Katukele'
 'Suduhumpala East' 'Bowalawatta' 'Poorna Watta East' 'Ihala Dodamwala'
 'Sirimalwatta West' 'Sirimalwatta East' 'Ampitiya Pallegama' 'Batagalla'
 'Uda Bowala' 'Kotagepitiya' 'Watapuluwa West' 'Hanthana Pedesa'
 'Ampitiya North' 'Nagasthenna' 'Bahirawa Kanda' 'Getambe' 'Nittawela'
 'Pallegunnepana North' 'Lewella' 'Mahaweli Uyana' 'Hippola'
 'Pitakanda Gama' 'Deiyannewela' 'Ampitiya South' 'Kendakaduwa'
 'Watapuluwa South' 'Kumburegedara' 'Kundasale North' 'Watapuluwa'
 'Pallegunnepana South' 'Dehiwatta' 'Palle Peradeniya' 'Katukele'
 'Ogastawatta' 'Aniwatta West' 'Meddegama' 'Inguruwatta' 'Wattegama North'
 'Kalugalawatta' 'Malwatta' 'Pitakanda' 'Mulgampala'
 'Gurudeniya Dambawela' 'Wewathenna' 'Godagandeniya' 'Haloluwa'
 'Uduwelawatta Colony' 'Uda Eriyagama East' 'Arangala South'
 'Wathurakumbura' 'Mapanawathura' 'Thalathuoya West' 'Ulpathakumbura']
gn_pcode :  ['LK2130170' 'LK2130105' 'LK2139135' 'LK2130100' 'LK2130050' 'LK2130165'
 'LK2130065' 'LK2130135' 'LK2130085' 'LK2130240' 'LK2130205' 'LK2130120'
 'LK2130130' 'LK2130235' 'LK2145090' 'LK2130080' 'LK2130145' 'LK2130115'
 'LK2130160' 'LK2130300' 'LK2130075' 'LK2136120' 'LK2127180' 'LK2127185'
 'LK2130245' 'LK2145100' 'LK2130200' 'LK2148125' 'LK2130060' 'LK2130220'
 'LK2130230' 'LK2130155' 'LK2130090' 'LK2130180' 'LK2130030' 'LK2127175'
 'LK2130125' 'LK2130040' 'LK2145035' 'LK2130015' 'LK2130150' 'LK2130225'
 'LK2136410' 'LK2130045' 'LK2133415' 'LK2127355' 'LK2130035' 'LK2127170'
 'LK2106015' 'LK2130195' 'LK2130110' 'LK2130305' 'LK2130175' 'LK2130250'
 'LK2142075' 'LK2112075' 'LK2112245' 'LK2130140' 'LK2154140' 'LK2130210'
 'LK2130285' 'LK2142095' 'LK2130190' 'LK2133410' 'LK2145005' 'LK2136420'
 'LK2127340' 'LK2136045' 'LK2130070' 'LK2145045' 'LK2130265' 'LK2130260']
gn_population :  [21826  8913 16411  1107  1293 18808 11543  2310  1314 19383  2430 11613
 19105   931 18993 17006  2198  6925 18807  2441 17005  6861 18568 18565
   928  1785 19819 10224 21493  5949   926 13921  1508  5235 14729 15562
 11008 11727  6481 16716  3143   929  9219 21491 10691 10716 21490 15563
  3133 15522  8909 14865  1109 12845  7300 21578  8028 12099 16712 13665
  5635 22268  5339  5808 20253 19822  1211 21541 12324 18994 20351 22267]
gn_distance_m :  [311.8 352.4 518.6 ... 315.  335.7 370. ]
victim_ethnicity  :  ['muslim' 'sinhala' 'tamil']
DS_Division :  ['Gangawata Korale' 'Udunuwara' 'Pathahewaheta' 'Yatinuwara' 'Kundasale'
 'Deltota' 'Harispattuwa' 'Poojapitiya' 'Doluwa' 'Pathadumbara'
 'Ganga Ihala Korale']
Avg_Household_Income :  [124797 111768  69786 ... 104448 112595 118896]
Unemployment_Rate :  [4.55 4.53 5.57 4.68 4.71 4.32 4.6  4.58 4.7  4.28 4.36 4.31 4.43 7.49
 4.66 4.64 4.69 4.38 4.42 4.47 4.67 4.49 4.56 4.52 4.35 5.83 5.46 5.25
 4.62 4.41 7.17 4.34 4.61 4.39 6.65 4.5  4.44 4.51 4.57 4.59 5.4  4.29
 7.05 4.48 4.37 4.46 4.54 4.72 4.65 4.4  5.8  4.63 4.3  6.06 5.88 5.31
 5.35 4.33 5.6  5.72 6.93 5.39 5.5  4.45 5.19 5.71 7.48 7.31 6.26 6.32
 5.86 8.18 8.13 5.64 5.94 5.95 6.   5.21 6.02 7.41 7.25 5.22 5.65 5.74
 7.43 5.99 5.62 7.53 6.5  7.45 5.41 6.1  5.42 7.11 5.56 5.55 6.18 5.34
 5.28 5.54 5.79 5.63 6.83 7.12 5.36 5.43 5.48 5.53 6.74 5.37 7.91 7.28
 6.58 5.13 6.12 6.98 5.7  7.06 7.72 5.66 7.   7.23 5.92 5.51 5.15 5.98
 7.07 7.59 6.04 7.89 6.13 5.47 7.09 5.23]
Building_Density :  [7.4090e+02 8.9270e+02 5.4840e+02 8.8120e+02 5.8540e+02 7.7540e+02
 6.6570e+02 5.7640e+02 9.9980e+02 4.8500e+01 5.1010e+02 8.0090e+02
 5.0500e+02 5.6110e+02 1.7600e+02 1.1235e+03 2.9330e+02 5.2290e+02
 8.9910e+02 6.6060e+02 8.2000e+02 8.4680e+02 1.2855e+03 8.0980e+02
 9.6410e+02 3.1880e+02 8.9650e+02 1.1656e+03 2.9710e+02 9.7430e+02
 2.5500e+01 1.1057e+03 5.2030e+02 6.1720e+02 1.0037e+03 6.8100e+02
 7.2560e+02 1.2240e+02 7.7000e+00 9.3220e+02 7.1400e+01 8.1620e+02
 5.9810e+02 1.2370e+02 5.7260e+02 8.0340e+02 1.2128e+03 1.5810e+02
 8.9020e+02 8.3020e+02 9.2710e+02 0.0000e+00 8.8250e+02 9.9220e+02
 6.1850e+02 8.8630e+02 4.3400e+01 8.0730e+02 8.6850e+02 8.4420e+02
 1.0827e+03 8.5570e+02 6.3000e+02 7.9710e+02 7.1930e+02 4.3360e+02
 1.0980e+03 9.8200e+02 7.3070e+02 8.3530e+02 2.3590e+02 8.0850e+02
 1.1439e+03 1.0916e+03 7.9070e+02 1.2630e+02 3.8640e+02 6.7970e+02
 1.0802e+03 9.6900e+01 1.4232e+03 3.3800e+02 2.2830e+02 3.3200e+01
 8.7870e+02 3.9150e+02 9.5010e+02 5.4450e+02 8.5060e+02 6.4020e+02
 7.3460e+02 7.1670e+02 8.7990e+02 9.3350e+02 9.4500e+02 3.9530e+02
 8.6210e+02 7.2310e+02 1.0177e+03 1.0814e+03 7.0780e+02 7.6260e+02
 1.3123e+03 1.3174e+03 1.0580e+02 8.8890e+02 4.5780e+02 8.5400e+01
 8.3910e+02 8.1240e+02 5.8150e+02 9.0670e+02 6.4150e+02 3.8000e+02
 7.8180e+02 6.4270e+02 1.2000e+03 7.9200e+02 5.3050e+02 1.3786e+03
 1.3327e+03 7.6900e+02 1.2166e+03 6.2230e+02 8.6700e+01 1.0710e+02
 8.4810e+02 2.0530e+02 5.2300e+01 1.0024e+03 8.7480e+02 4.8590e+02
 6.4660e+02 1.4475e+03 8.2510e+02 3.0730e+02 6.1340e+02 8.1490e+02
 2.9300e+01 6.1200e+01 8.5190e+02 3.7750e+02 1.2115e+03 7.4480e+02
 9.7300e+02 1.5560e+02 4.4640e+02 5.1270e+02 8.3790e+02 5.8920e+02
 2.6270e+02 1.2141e+03 1.0725e+03 4.2590e+02 8.2260e+02 7.5240e+02
 3.4560e+02 9.9090e+02 1.0151e+03 8.6720e+02 5.2670e+02 1.1210e+03
 6.2110e+02 6.2360e+02 7.7800e+01 3.6730e+02 5.5220e+02 1.1730e+02
 6.9630e+02 4.2980e+02 8.2900e+01 1.0200e+01 3.8000e+00 6.4000e+00
 4.0550e+02 7.4990e+02 7.4000e+01 1.3021e+03 8.8380e+02 8.2380e+02
 2.8310e+02 6.5290e+02 7.7410e+02 1.2500e+02 2.4230e+02 6.9890e+02
 1.0763e+03 8.8760e+02 5.9900e+01 9.3610e+02 5.8410e+02 7.3580e+02
 8.4550e+02 1.4640e+03 8.5950e+02 2.8100e+01 8.3150e+02 9.7560e+02
 7.8940e+02 6.0700e+02 6.7460e+02 7.7280e+02 4.6290e+02 1.0317e+03

In [11]:
print("Unique values")
for col in categorical_cols:
  # print(f"{col} : ",df[col].unique())
  print(f"{col} : ",df[col].nunique())

Unique values
crime :  6
location :  125
date :  1046
sex :  3
victim_ethnicity :  3
victim_age :  64
time :  916
weather :  3
latitude :  1605
longitude :  1605
holiday_name :  28
is_holiday :  2
land_use_type :  4
gn_division :  71
gn_pcode :  72
gn_population :  72
gn_distance_m :  1419
victim_ethnicity  :  3
DS_Division :  11
Avg_Household_Income :  1571
Unemployment_Rate :  134
Building_Density :  729
Road_Density :  280
Land_Area_Density :  1009

##Aggregate to : GN Division & Time Window

In [12]:
#Create weekly time windows
df['week'] = df['date'].dt.to_period('W').apply(lambda r: r.start_time)

In [13]:
#Aggregate to GN Division, Time Window


aggregated_df = (
    df.groupby(['gn_division', 'week'])
      .agg(
          #crime counts (targets)
          total_crimes=('crime', 'count'),

          burglary_count=('crime', lambda x: x.str.contains('burglary', case=False).sum()),
          theft_count=('crime', lambda x: (x == 'theft').sum()),
          vehicle_count=('crime', lambda x: x.str.contains('vehicle', case=False).sum()),
          robbery_count=('crime', lambda x: x.str.contains('robbery', case=False).sum()),
          drugs_count=('crime', lambda x: x.str.contains('drugs', case=False).sum()),
          stabbing_count=('crime', lambda x: x.str.contains('stabbing', case=False).sum()),

          #demographic context (ethical aggregation)
          avg_victim_age=('victim_age', 'mean'),
          female_victim_ratio=('sex', lambda x: (x == 'f').mean()),

          #spacial/environmental context - GN-level spatial exposure variables
          population=('gn_population', 'first'), #Population = exposure size
          mean_distance_m=('gn_distance_m', 'mean'), #Distance = accessibility / remoteness
          urban_ratio=('land_use_type', lambda x: (x == 'General Urban').mean()), # Urban ratio = land-use intensity

          #Temporal context
          #Proportion of days in the week that were: holidays, rainy
          holiday_ratio=('is_holiday', 'mean'),
          rainy_ratio=('weather', lambda x: (x.str.lower() == 'rainy').mean()),

          ds_division=('DS_Division', 'first')
      )
      .reset_index()
)

##Create complete GN×Week grid (zero-crime weeks)

In [14]:
all_gn = aggregated_df['gn_division'].unique()
all_weeks = pd.date_range(
    aggregated_df['week'].min(),
    aggregated_df['week'].max(),
    freq='W-MON'
)

full_index = pd.MultiIndex.from_product(
    [all_gn, all_weeks],
    names=['gn_division', 'week']
)

completed_df = (
    full_index.to_frame(index=False)
    .merge(aggregated_df, on=['gn_division', 'week'], how='left')
)

crime_cols = [
    'total_crimes','burglary_count','theft_count',
    'vehicle_count','robbery_count','drugs_count','stabbing_count'
]

completed_df[crime_cols] = completed_df[crime_cols].fillna(0)


completed_df['avg_victim_age'] = (
    completed_df.groupby('gn_division')['avg_victim_age']
                .transform(lambda x: x.fillna(x.median()))
)


ratio_cols = ['female_victim_ratio','urban_ratio','holiday_ratio','rainy_ratio']
completed_df[ratio_cols] = completed_df[ratio_cols].fillna(0)

# Enure Every GN-week row gets a valid population and distance value
completed_df[['population','mean_distance_m']] = (
    completed_df.groupby('gn_division')[['population','mean_distance_m']]
                .ffill().bfill()
)

##Integrate demographic & environmental variables

In [15]:
context_cols = [
    'Unemployment_Rate',
    'Building_Density',
    'Avg_Household_Income',
    'Land_Area_Density',
    'Road_Density'
]

for col in context_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

gn_context = (
    df.groupby('gn_division')
      .agg(
          unemployment_rate=('Unemployment_Rate', 'mean'),
          avg_income=('Avg_Household_Income', 'mean'),
          building_density=('Building_Density', 'mean'),
          land_area_density=('Land_Area_Density', 'mean'),
          road_density=('Road_Density', 'mean'),
          ds_division=('DS_Division', 'first')
      )
      .reset_index()
)

completed_df = completed_df.merge(
    gn_context,
    on='gn_division',
    how='left'
)

##Feature engineering (final feature table)

In [16]:
df_features = completed_df.copy()

# Time features
df_features['year'] = df_features['week'].dt.year
df_features['week_of_year'] = df_features['week'].dt.isocalendar().week.astype(int)

df_features['week_sin'] = np.sin(2*np.pi*df_features['week_of_year']/52)
df_features['week_cos'] = np.cos(2*np.pi*df_features['week_of_year']/52)

# Scale-friendly transforms
df_features['log_population'] = np.log1p(df_features['population'])
df_features['distance_km'] = df_features['mean_distance_m'] / 1000

df_features.drop(
    columns=['week','week_of_year','population','mean_distance_m'],
    inplace=True
)

df_features[crime_cols] = df_features[crime_cols].astype(int)

##Dependent variable management (clean & final)

In [17]:
df_features.rename(columns={'ds_division_y': 'ds_division'}, inplace=True)

df_features.drop(columns=['ds_division_x'], inplace=True)

df_features['ds_division'].isna().sum()

np.int64(0)

In [18]:
df_features.to_csv("df_features.csv", index=False)

from google.colab import files
files.download("df_features.csv")

In [19]:
df_model = df_features.copy()

In [20]:
crime_types = {
    'burglary':'y_burglary',
    'theft':'y_theft',
    'vehicle':'y_vehicle',
    'robbery':'y_robbery',
    'drugs':'y_drugs',
    'stabbing':'y_stabbing'
}

In [21]:
# Create binary targets

df_model['y_burglary'] = (df_model['burglary_count'] > 0).astype(int)
df_model['y_theft'] = (df_model['theft_count'] > 0).astype(int)
df_model['y_vehicle'] = (df_model['vehicle_count'] > 0).astype(int)
df_model['y_robbery'] = (df_model['robbery_count'] > 0).astype(int)
df_model['y_drugs'] = (df_model['drugs_count'] > 0).astype(int)
df_model['y_stabbing'] = (df_model['stabbing_count'] > 0).astype(int)

In [22]:
leakage_cols = [
    # Spatial identifiers (NOT causal features)
    'gn_division',
    'ds_division',

    # Direct outcome leakage
    'total_crimes',

    # Crime-type counts (post-event information)
    'burglary_count',
    'theft_count',
    'vehicle_count',
    'robbery_count',
    'drugs_count',
    'stabbing_count',

    # Binary targets (never in X)
    'y_burglary',
    'y_theft',
    'y_vehicle',
    'y_robbery',
    'y_drugs',
    'y_stabbing'
]

In [23]:
#Time-aware train test split

In [24]:
df_model['week'] = completed_df['week'].values

# sort by time
df_model = df_model.sort_values(by='week').reset_index(drop=True)

#define X and y for each crime type
target_cols = [
    'y_burglary',
    'y_theft',
    'y_vehicle',
    'y_robbery',
    'y_drugs',
    'y_stabbing'
]

X = df_model.drop(columns=leakage_cols + ['week'])

for col in target_cols:
  target_col = col
  y = df_model[target_col]

  # perform the chronological split
  split_index = int(len(df_model)* 0.8)

  X_train = X.iloc[:split_index]
  X_test = X.iloc[split_index:]

  y_train = y.iloc[:split_index]
  y_test = y.iloc[split_index:]


  print("Train size: ",X_train.shape)
  print("Test size: ",X_test.shape)

  print("\nTarget distribution (train):")
  print(y_train.value_counts(normalize=True))

  print("\nTarget distribution (test):")
  print(y_test.value_counts(normalize=True))

Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_burglary
0    0.97811
1    0.02189
Name: proportion, dtype: float64

Target distribution (test):
y_burglary
0    0.988498
1    0.011502
Name: proportion, dtype: float64
Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_theft
0    0.984214
1    0.015786
Name: proportion, dtype: float64

Target distribution (test):
y_theft
0    0.991549
1    0.008451
Name: proportion, dtype: float64
Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_vehicle
0    0.994953
1    0.005047
Name: proportion, dtype: float64

Target distribution (test):
y_vehicle
0    0.997653
1    0.002347
Name: proportion, dtype: float64
Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_robbery
0    0.986796
1    0.013204
Name: proportion, dtype: float64

Target distribution (test):
y_robbery
0    0.993897
1    0.006103
Name: proportion, dtype: float64
Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_drugs
0    0.987089
1    0.012911
Name: proportion, dtype: float64

Target distribution (test):
y_drugs
0    0.994131
1    0.005869
Name: proportion, dtype: float64
Train size:  (17040, 15)
Test size:  (4260, 15)

Target distribution (train):
y_stabbing
0    0.989202
1    0.010798
Name: proportion, dtype: float64

Target distribution (test):
y_stabbing
0    0.99554
1    0.00446
Name: proportion, dtype: float64

In [25]:
# Scaling and Normalization

In [26]:
from sklearn.preprocessing import StandardScaler

scale_cols = ['avg_victim_age','unemployment_rate','avg_income','building_density','land_area_density','road_density','log_population','distance_km','year']

scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test_scaled[scale_cols] = scaler.transform(X_test[scale_cols])

X_train_scaled[scale_cols].describe().loc[['mean','std']]

,avg_victim_age,unemployment_rate,avg_income,building_density,land_area_density,road_density,log_population,distance_km,year
mean,-4.512822e-16,-8.889603e-16,-4.982973e-16,2.851136e-17,7.946174e-17,-5.141948e-17,-8.421537e-16,3.825839e-17,1.467788e-16
std,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00

In [27]:
X_test_scaled[scale_cols].describe().loc[['mean','std']]

,avg_victim_age,unemployment_rate,avg_income,building_density,land_area_density,road_density,log_population,distance_km,year
mean,0.011616,-8.910973e-16,-4.988185e-16,2.772951e-17,7.776773e-17,-5.003822e-17,-3.013142e-07,-0.015317,2.091509
std,0.950522,1.000117e+00,1.000117e+00,1.000117e+00,1.000117e+00,1.000117e+00,1.000117e+00,0.988813,0.357343

# Baseline Model Training

In [28]:
# Fitting the baseline logistic regression

from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression(max_iter=1000,
                                  class_weight='balanced',
                                  solver='lbfgs',
                                  random_state=42
                                  )

logreg_model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [29]:
# Get predictions

# Binary predictions
y_predict = logreg_model.predict(X_test_scaled)

# Probability predictions
y_predic_proba = logreg_model.predict_proba(X_test_scaled)[:, 1]

In [30]:
# Evaluate

from sklearn.metrics import(
    classification_report,
    roc_auc_score,
    confusion_matrix
)

print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98      4241
           1       0.12      1.00      0.22        19

    accuracy                           0.97      4260
   macro avg       0.56      0.98      0.60      4260
weighted avg       1.00      0.97      0.98      4260

In [31]:
# ROC-AUC
roc_auc_logrg=roc_auc_score(y_test, y_predic_proba)
print("ROC-AUC:",roc_auc_logrg)

ROC-AUC: 0.9869941299842392

In [32]:
# Interpreting coefficients - the key causal output

coef_df = pd.DataFrame({
    'feature': X_train_scaled.columns,
    'coefficient': logreg_model.coef_[0]
})

coef_df.sort_values(by='coefficient', ascending=False)

coef_df

                feature  coefficient
0        avg_victim_age    -0.150392
1   female_victim_ratio     1.371734
2           urban_ratio     3.395979
3         holiday_ratio     0.285645
4           rainy_ratio     3.664383
5     unemployment_rate    -0.239243
6            avg_income     0.312270
7      building_density    -0.811048
8     land_area_density     1.825599
9          road_density    -0.749977
10                 year     0.039991
11             week_sin     0.774925
12             week_cos     0.300842
13       log_population    -0.080335
14          distance_km    -0.360588

In [33]:
# Fitting the random forest model

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)


rf_model.fit(X_train_scaled, y_train)

# Get predictions
# Binary predictions
y_predict_rf = rf_model.predict(X_test_scaled)

# probability predictions
y_predict_proba_rf = rf_model.predict_proba(X_test_scaled)[:, 1]

In [34]:
# Evaluate
from sklearn.metrics import classification_report, roc_auc_score

# classification report
print(classification_report(y_test, y_predict_rf))

# roc-auc
roc_auc_rf = roc_auc_score(y_test, y_predict_proba_rf)
print("Random Forest ROC-AUC:", roc_auc_rf)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      4241
           1       0.23      0.37      0.28        19

    accuracy                           0.99      4260
   macro avg       0.61      0.68      0.64      4260
weighted avg       0.99      0.99      0.99      4260

Random Forest ROC-AUC: 0.9846113751721912

In [35]:
# Model Benchmarking

from sklearn.metrics import precision_score, recall_score, f1_score
benchmark_results = []

# Logistic regression
benchmark_results.append({
    'Model': 'Logistic Regression',
    'ROC-AUC': roc_auc_logrg,
    'Precision':precision_score(y_test, y_predict),
    'Recall':recall_score(y_test, y_predict),
    'F1-Score':f1_score(y_test, y_predict)
})

# Random Forest
benchmark_results.append({
    'Model': 'Random Forest',
    'ROC-AUC': roc_auc_rf,
    'Precision':precision_score(y_test, y_predict_rf),
    'Recall':recall_score(y_test, y_predict_rf),
    'F1-Score':f1_score(y_test, y_predict_rf)
})

benchmark_df = pd.DataFrame(benchmark_results)
benchmark_df

                 Model   ROC-AUC  Precision    Recall  F1-Score
0  Logistic Regression  0.986994   0.125000  1.000000  0.222222
1        Random Forest  0.984611   0.225806  0.368421  0.280000

# Hyperparameter Tuning

In [36]:
# Time-aware validation split

val_split_index = int(len(X_train_scaled)*0.8)

X_train_sub = X_train_scaled.iloc[:val_split_index]
y_train_sub = y_train.iloc[:val_split_index]

X_val = X_train_scaled.iloc[val_split_index:]
y_val = y_train.iloc[val_split_index:]

In [37]:
# Hyperparameter grid
param_grid = {
    'n_estimators':[200,400],
    'max_depth':[None,10,20],
    'min_samples_leaf':[3,5,10],
    'max_features':['sqrt',0.5]
}

In [38]:
# Manual grid search

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
import itertools

best_auc = 0
best_model = None
best_params = None

for params in itertools.product(
    param_grid['n_estimators'],
    param_grid['max_depth'],
    param_grid['min_samples_leaf'],
    param_grid['max_features']
):

  n_estimators, max_depth, min_samples_leaf, max_features = params

  rf_model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      min_samples_leaf=min_samples_leaf,
      max_features=max_features,
      class_weight ='balanced',
      random_state=42,
      n_jobs=-1
  )

  rf_model.fit(X_train_sub, y_train_sub)

  y_val_proba = rf_model.predict_proba(X_val)[:,1]
  auc = roc_auc_score(y_val, y_val_proba)

  if auc > best_auc:
    best_auc = auc
    best_model = rf_model
    best_params = {
        'n_estimators':n_estimators,
        'max_depth':max_depth,
        'min_samples_leaf':min_samples_leaf,
        'max_features':max_features
    }

print("Best AUC (validation): ", best_auc)
print("Best parameters: ",best_params)

Best AUC (validation):  0.9727049483147046
Best parameters:  {'n_estimators': 200, 'max_depth': 20, 'min_samples_leaf': 3, 'max_features': 'sqrt'}

In [39]:
# Refiting the best random forest model on full training data
rf_tuned = RandomForestClassifier(
    **best_params,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_tuned.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=20,
                       min_samples_leaf=3, n_estimators=200, n_jobs=-1,
                       random_state=42)

In [40]:
# Evaluate the tuned model
y_pred_rf_tuned = rf_tuned.predict(X_test_scaled)
y_pred_proba_rf_tuned = rf_tuned.predict_proba(X_test_scaled)[:,1]

print(classification_report(y_test, y_pred_rf_tuned))
print("Tuned RF ROC AUC: ",
      roc_auc_score(y_test, y_pred_proba_rf_tuned))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4241
           1       0.14      0.11      0.12        19

    accuracy                           0.99      4260
   macro avg       0.57      0.55      0.56      4260
weighted avg       0.99      0.99      0.99      4260

Tuned RF ROC AUC:  0.9830104617828467

# SHAP Explanations

In [41]:
# Setting up SHAP for the tuned Random Forest
import shap
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
# Influence of each causative factors on a given crime type throught Kandy
# Municipal council (All GN Divisions)

def get_global_summary_table(shap_values_pos, feature_names):
  mean_abs_shap = np.abs(shap_values_pos).mean(axis=0)
  return (
      pd.DataFrame({
          'feature':feature_names,
          'mean_abs_shap':mean_abs_shap
      })
      .sort_values(by='mean_abs_shap',ascending=False)
  )

In [43]:
# Increase or Decrease effect of each causative factor on a given crime type throught Kandy
# Municipal council (All GN Divisions)

def get_global_directional_effect_table(shap_values_pos, X):
  effects = {}
  for i, col in enumerate(X.columns):
    corr = np.corrcoef(X[col], shap_values_pos[:,i])[0,1]
    effects[col] = 'increases risk' if corr > 0 else 'decreases risk'
  return effects

In [44]:
# Influence of each causative factor on a given crime type in a given GN Divisions)

def get_local_top_drivers(shap_row, X_row, top_k=3):
  contribs = pd.DataFrame({
      'feature':X_row.index,
      'shap_value':shap_row,
      'feature_value':X_row.values
  })
  return contribs.reindex(
      contribs.shap_value.abs().sort_values(ascending=False).index
  ).head(top_k)

In [45]:
# Automating explanative interpretation
def local_explanation(crime_type, gn_division, top_drivers):
  drivers = ",".join(top_drivers['feature'].values[:2])
  mitigator = top_drivers['feature'].values[-1]

  return(
      f"The elevated {crime_type} risk in {gn_division} during the pask week "
      f"is primarily driven by {drivers}, which outweigh mitigating facors "
      f" such as {mitigator}"
  )

In [46]:
def shap_crime(crime_name, target_col, df_model, X, scale_cols):
  print(f"Causative Factors for {crime_name}")

  # Target
  y=df_model[target_col]

  # Time aware split
  split_index = int(len(df_model)* 0.8)

  X_train = X.iloc[:split_index]
  X_test = X.iloc[split_index:]

  y_train = y.iloc[:split_index]
  y_test = y.iloc[split_index:]


  # Scaling
  scale_cols = ['avg_victim_age','unemployment_rate','avg_income','building_density','land_area_density','road_density','log_population','distance_km','year']

  # Fit scaler on train
  scaler = StandardScaler()

  X_train_scaled = X_train.copy()
  X_test_scaled = X_test.copy()

  X_train_scaled[scale_cols] = scaler.fit_transform(X_train[scale_cols])
  X_test_scaled[scale_cols] = scaler.transform(X_test[scale_cols])



  # Random Forest
  rf_model = RandomForestClassifier(
      n_estimators= 200,
      max_depth= 20,
      min_samples_leaf= 3,
      max_features= 'sqrt',
      class_weight ='balanced',
      random_state=42,
      n_jobs=-1
  )
  rf_model.fit(X_train_scaled, y_train)

  y_pred_proba_rf= rf_model.predict_proba(X_test_scaled)[:,1]


  # SHAP

  explainer = shap.TreeExplainer(rf_model)

  shap_values = explainer.shap_values(X_test_scaled)

  shap_values_pos = shap_values[:,:,1]
  base_value = explainer.expected_value[1]

  global_summary = get_global_summary_table(shap_values_pos, X_test_scaled.columns)

  dirrectional_effect = get_global_directional_effect_table(shap_values_pos, X_test_scaled)


  local_results = []

  for i in range(len(X_test_scaled)):
    top_drivers = get_local_top_drivers(shap_values_pos[i],X_test_scaled.iloc[i])

    local_results.append({
        'gn_division':df_model.loc[X_test.index[i],'gn_division'],
        'week':df_model.loc[X_test.index[i],'week'],
        'risk_score':y_pred_proba_rf[i],
        'top_features':list(top_drivers['feature']),
        'explanation_text':local_explanation(crime_name,df_model.loc[X_test.index[i],'gn_division'],top_drivers)
    })

  return {
      'model':rf_model,
      'global_summary':global_summary,
      'dirrectional_effect':dirrectional_effect,
      'local_results':local_results
  }

In [47]:
# Running Time-aware split,scailing and SHAP for all the crime types

results = {}

for crime_name, target_col in crime_types.items():
  results[crime_name] = shap_crime(
      crime_name,
      target_col,
      df_model,
      X,
      scale_cols
  )

Causative Factors for burglary
Causative Factors for theft
Causative Factors for vehicle
Causative Factors for robbery
Causative Factors for drugs
Causative Factors for stabbing

In [48]:
for crime, result in results.items():
    print(f"\n{crime.upper()} EXPLANATION:")
    for row in result['local_results']:
        # Ensure risk_score is a scalar before formatting
        # If risk_score is an ndarray, take its mean. If it's already a scalar, np.mean will return it.
        risk_score_scalar = np.mean(row['risk_score'])
        print(
            f"{row['week'].date()} | {row['gn_division']} | "
            f"Risk={risk_score_scalar:.3f}"
        )
        print(" →", row['explanation_text'])

Streaming output truncated to the last 5000 lines.
2025-01-20 | Mapanawathura | Risk=0.015
 → The elevated stabbing risk in Mapanawathura during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-20 | Lewella | Risk=0.000
 → The elevated stabbing risk in Lewella during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-20 | Thennakumbura | Risk=0.019
 → The elevated stabbing risk in Thennakumbura during the pask week is primarily driven by distance_km,urban_ratio, which outweigh mitigating facors  such as rainy_ratio
2025-01-20 | Kotagepitiya | Risk=0.000
 → The elevated stabbing risk in Kotagepitiya during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-20 | Watapuluwa | Risk=0.000
 → The elevated stabbing risk in Watapuluwa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-20 | Getambe | Risk=0.020
 → The elevated stabbing risk in Getambe during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-20 | Godagandeniya | Risk=0.004
 → The elevated stabbing risk in Godagandeniya during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-20 | Bogambara | Risk=0.015
 → The elevated stabbing risk in Bogambara during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-20 | Suduhumpala East | Risk=0.008
 → The elevated stabbing risk in Suduhumpala East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-20 | Hippola | Risk=0.001
 → The elevated stabbing risk in Hippola during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-20 | Ihala Katukele | Risk=0.010
 → The elevated stabbing risk in Ihala Katukele during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-20 | Malwatta | Risk=0.000
 → The elevated stabbing risk in Malwatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as land_area_density
2025-01-20 | Palle Peradeniya | Risk=0.005
 → The elevated stabbing risk in Palle Peradeniya during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-20 | Kendakaduwa | Risk=0.017
 → The elevated stabbing risk in Kendakaduwa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-20 | Kalugalawatta | Risk=0.000
 → The elevated stabbing risk in Kalugalawatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Sirimalwatta West | Risk=0.000
 → The elevated stabbing risk in Sirimalwatta West during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Katukele West | Risk=0.003
 → The elevated stabbing risk in Katukele West during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Ulpathakumbura | Risk=0.000
 → The elevated stabbing risk in Ulpathakumbura during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-27 | Uduwelawatta Colony | Risk=0.000
 → The elevated stabbing risk in Uduwelawatta Colony during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Haloluwa | Risk=0.002
 → The elevated stabbing risk in Haloluwa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Nittawela | Risk=0.000
 → The elevated stabbing risk in Nittawela during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Arangala South | Risk=0.000
 → The elevated stabbing risk in Arangala South during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Bogambara | Risk=0.020
 → The elevated stabbing risk in Bogambara during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Thalathuoya West | Risk=0.000
 → The elevated stabbing risk in Thalathuoya West during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Kumburegedara | Risk=0.003
 → The elevated stabbing risk in Kumburegedara during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Mahaweli Uyana | Risk=0.005
 → The elevated stabbing risk in Mahaweli Uyana during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Pitakanda Gama | Risk=0.000
 → The elevated stabbing risk in Pitakanda Gama during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Sirimalwatta East | Risk=0.000
 → The elevated stabbing risk in Sirimalwatta East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Hippola | Risk=0.001
 → The elevated stabbing risk in Hippola during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Thalathuoya East | Risk=0.000
 → The elevated stabbing risk in Thalathuoya East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Wathurakumbura | Risk=0.000
 → The elevated stabbing risk in Wathurakumbura during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-27 | Uda Bowala | Risk=0.002
 → The elevated stabbing risk in Uda Bowala during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as land_area_density
2025-01-27 | Aruppala East | Risk=0.000
 → The elevated stabbing risk in Aruppala East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_income
2025-01-27 | Ampitiya South | Risk=0.000
 → The elevated stabbing risk in Ampitiya South during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Watapuluwa West | Risk=0.024
 → The elevated stabbing risk in Watapuluwa West during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as log_population
2025-01-27 | Aniwatta East | Risk=0.007
 → The elevated stabbing risk in Aniwatta East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Nagasthenna | Risk=0.000
 → The elevated stabbing risk in Nagasthenna during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Watapuluwa | Risk=0.000
 → The elevated stabbing risk in Watapuluwa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-27 | Wattegama North | Risk=0.000
 → The elevated stabbing risk in Wattegama North during the pask week is primarily driven by rainy_ratio,log_population, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Penideniya | Risk=0.000
 → The elevated stabbing risk in Penideniya during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Hanthana Pedesa | Risk=0.621
 → The elevated stabbing risk in Hanthana Pedesa during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as week_sin
2025-01-27 | Mahaiyawa | Risk=0.011
 → The elevated stabbing risk in Mahaiyawa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Aniwatta West | Risk=0.003
 → The elevated stabbing risk in Aniwatta West during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as road_density
2025-01-27 | Suduhumpala West | Risk=0.011
 → The elevated stabbing risk in Suduhumpala West during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as road_density
2025-01-27 | Gurudeniya Dambawela | Risk=0.000
 → The elevated stabbing risk in Gurudeniya Dambawela during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Mulgampala | Risk=0.004
 → The elevated stabbing risk in Mulgampala during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_income
2025-01-27 | Thennakumbura | Risk=0.019
 → The elevated stabbing risk in Thennakumbura during the pask week is primarily driven by distance_km,urban_ratio, which outweigh mitigating facors  such as rainy_ratio
2025-01-27 | Suduhumpala East | Risk=0.008
 → The elevated stabbing risk in Suduhumpala East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Getambe | Risk=0.020
 → The elevated stabbing risk in Getambe during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Lewella | Risk=0.000
 → The elevated stabbing risk in Lewella during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Kundasale North | Risk=0.000
 → The elevated stabbing risk in Kundasale North during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Uda Eriyagama East | Risk=0.003
 → The elevated stabbing risk in Uda Eriyagama East during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Ihala Dodamwala | Risk=0.000
 → The elevated stabbing risk in Ihala Dodamwala during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Ihala Katukele | Risk=0.010
 → The elevated stabbing risk in Ihala Katukele during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Mahanuwara | Risk=0.013
 → The elevated stabbing risk in Mahanuwara during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Ampitiya Udagama North | Risk=0.000
 → The elevated stabbing risk in Ampitiya Udagama North during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Pallegunnepana South | Risk=0.008
 → The elevated stabbing risk in Pallegunnepana South during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Watapuluwa South | Risk=0.008
 → The elevated stabbing risk in Watapuluwa South during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-27 | Thalwatta | Risk=0.005
 → The elevated stabbing risk in Thalwatta during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Poorna Watta East | Risk=0.000
 → The elevated stabbing risk in Poorna Watta East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_income
2025-01-27 | Kendakaduwa | Risk=0.017
 → The elevated stabbing risk in Kendakaduwa during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Pitakanda | Risk=0.000
 → The elevated stabbing risk in Pitakanda during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Kalugalawatta | Risk=0.000
 → The elevated stabbing risk in Kalugalawatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Kotagepitiya | Risk=0.000
 → The elevated stabbing risk in Kotagepitiya during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Godagandeniya | Risk=0.004
 → The elevated stabbing risk in Godagandeniya during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Deiyannewela | Risk=0.002
 → The elevated stabbing risk in Deiyannewela during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Meddegama | Risk=0.000
 → The elevated stabbing risk in Meddegama during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Ampitiya North | Risk=0.005
 → The elevated stabbing risk in Ampitiya North during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Palle Peradeniya | Risk=0.005
 → The elevated stabbing risk in Palle Peradeniya during the pask week is primarily driven by urban_ratio,rainy_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Ampitiya Pallegama | Risk=0.000
 → The elevated stabbing risk in Ampitiya Pallegama during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Asgiriya | Risk=0.012
 → The elevated stabbing risk in Asgiriya during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Inguruwatta | Risk=0.000
 → The elevated stabbing risk in Inguruwatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Wewathenna | Risk=0.007
 → The elevated stabbing risk in Wewathenna during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-01-27 | Bowala | Risk=0.013
 → The elevated stabbing risk in Bowala during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Boowelikada | Risk=0.152
 → The elevated stabbing risk in Boowelikada during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Batagalla | Risk=0.000
 → The elevated stabbing risk in Batagalla during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Poorna Watta West | Risk=0.000
 → The elevated stabbing risk in Poorna Watta West during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Bowalawatta | Risk=0.003
 → The elevated stabbing risk in Bowalawatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as distance_km
2025-01-27 | Dehiwatta | Risk=0.000
 → The elevated stabbing risk in Dehiwatta during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Katukele | Risk=0.000
 → The elevated stabbing risk in Katukele during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Welata | Risk=0.000
 → The elevated stabbing risk in Welata during the pask week is primarily driven by rainy_ratio,log_population, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Pallegunnepana North | Risk=0.000
 → The elevated stabbing risk in Pallegunnepana North during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-01-27 | Mapanawathura | Risk=0.015
 → The elevated stabbing risk in Mapanawathura during the pask week is primarily driven by rainy_ratio,distance_km, which outweigh mitigating facors  such as urban_ratio
2025-01-27 | Malwatta | Risk=0.000
 → The elevated stabbing risk in Malwatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as land_area_density
2025-01-27 | Bahirawa Kanda | Risk=0.004
 → The elevated stabbing risk in Bahirawa Kanda during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-01-27 | Ogastawatta | Risk=0.003
 → The elevated stabbing risk in Ogastawatta during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as land_area_density
2025-02-03 | Deiyannewela | Risk=0.002
 → The elevated stabbing risk in Deiyannewela during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_victim_age
2025-02-03 | Meddegama | Risk=0.000
 → The elevated stabbing risk in Meddegama during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-02-03 | Aruppala East | Risk=0.000
 → The elevated stabbing risk in Aruppala East during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as avg_income
2025-02-03 | Batagalla | Risk=0.005
 → The elevated stabbing risk in Batagalla during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-02-03 | Kumburegedara | Risk=0.003
 → The elevated stabbing risk in Kumburegedara during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-02-03 | Pallegunnepana North | Risk=0.000
 → The elevated stabbing risk in Pallegunnepana North during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as unemployment_rate
2025-02-03 | Wewathenna | Risk=0.007
 → The elevated stabbing risk in Wewathenna during the pask week is primarily driven by rainy_ratio,urban_ratio, which outweigh mitigating facors  such as log_population
2025-02-03 | Kalugalawatta | Risk=0.000